# Generated by Django 2.1.5 on 2019-05-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_tag_divisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client_pronouns',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
