# Generated by Django 2.1.5 on 2019-12-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20191225_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='screening_asked',
            field=models.BooleanField(default=False, verbose_name='I asked the client the basic needs screening questions above'),
        ),
    ]
