# Generated by Django 2.1.5 on 2019-12-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_case_screening_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='dependent',
            field=models.BooleanField(default=False, verbose_name='Needs Dependent Assistance: "Are you financially supporting another person?" (Child, parent, significant other, etc.)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='semester_food',
            field=models.BooleanField(default=False, verbose_name='Needs Long-Term Food Assistance: "Do you have enough food for the duration of the semester?" (If the answer is NO, check the box)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='week_food',
            field=models.BooleanField(default=False, verbose_name='Needs Short-Term Food Assistance: "Do you have enough food for the week?" (If the student needs housing assistance, check the box)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='week_housing',
            field=models.BooleanField(default=False, verbose_name='Needs Housing Assistance: "Do you have a safe and stable home for tonight and the rest of this week?" (If the answer is NO, check the box)'),
        ),
    ]
