# Generated by Django 2.1.5 on 2019-12-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20191227_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='dependent',
            field=models.BooleanField(default=False, verbose_name='Needs Dependent Assistance: "Are you financially supporting another person?" (Child, parent, significant other, etc.) (If the answer is YES, check the box)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='week_food',
            field=models.BooleanField(default=False, verbose_name='Needs Short-Term Food Assistance: "Do you have enough food for the week?" (If the answer is NO, check the box)'),
        ),
    ]
