# Generated by Django 2.1.5 on 2019-12-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_auto_20191227_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='dependent',
            field=models.BooleanField(default=False, verbose_name='(IGNORE) Needs Dependent Assistance: "Are you financially supporting another person?" (Child, parent, significant other, etc.) (If the answer is YES, check the box)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='screening_asked',
            field=models.BooleanField(default=False, verbose_name='(IGNORE) I asked the client the basic needs screening questions above'),
        ),
        migrations.AlterField(
            model_name='case',
            name='semester_food',
            field=models.BooleanField(default=False, verbose_name='(IGNORE) Needs Long-Term Food Assistance: "Do you have enough food for the duration of the semester?" (If the answer is NO, check the box)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='week_food',
            field=models.BooleanField(default=False, verbose_name='(IGNORE) Needs Short-Term Food Assistance: "Do you have enough food for the week?" (If the answer is NO, check the box)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='week_housing',
            field=models.BooleanField(default=False, verbose_name='(IGNORE) Needs Housing Assistance: "Do you have a safe and stable home for tonight and the rest of this week?" (If the answer is NO, check the box)'),
        ),
    ]
