# Generated by Django 2.1.5 on 2019-12-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_auto_20191228_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='dependent',
            field=models.BooleanField(default=False, verbose_name='(IGNORE)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='screening_asked',
            field=models.BooleanField(default=False, verbose_name='(IGNORE)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='semester_food',
            field=models.BooleanField(default=False, verbose_name='(IGNORE)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='week_food',
            field=models.BooleanField(default=False, verbose_name='(IGNORE)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='week_housing',
            field=models.BooleanField(default=False, verbose_name='(IGNORE)'),
        ),
    ]
